In [1]:
import numpy as np

In [8]:
# Vectors

v = np.array([1,3,5,7,9])

print("shape:", v.shape, "size:", v.size)

shape: (5,) size: 5


In [24]:
# Matrix

m = np.array([[1,2,3], [3,4,5]])

print("shape:", m.shape, "size:", m.size)

shape: (2, 3) size: 6


In [25]:
print(m)

[[1 2 3]
 [3 4 5]]


In [52]:
# Tensors

t = np.array([[[1,2,3],[3,4,5]], [[0,1,2],[2,3,4]]])

print("shape:", t.shape, "size:", t.size)

shape: (2, 2, 3) size: 12


In [53]:
print(t)

[[[1 2 3]
  [3 4 5]]

 [[0 1 2]
  [2 3 4]]]


In [54]:
# Reshaping

v = np.array([1,3,5,7])

print("shape before:", v.shape)
v = v.reshape((1,4))
print("shape after:", v.shape)
v = v.reshape(1,1,4)
print("shape after:", v.shape)

shape before: (4,)
shape after: (1, 4)
shape after: (1, 1, 4)


In [60]:
# Slicing

v = np.array([[1,3,5,7], [3,4,5,6], [5,6,7,8]])

print(v[1,0:2])   # Slicing from second axis

[3 4]


In [61]:
# Element wise Matrix Operation

m = np.array([[1,2,3], [3,4,5]])
m = m + 3
print(m)

[[4 5 6]
 [6 7 8]]


In [75]:
# Matrix product

m = np.array([[1,2,3], [3,4,5]])
print("shape of m:", m.shape)

n = np.array([[0,2,1], [3,1,5], [8,1,0]])
print("shape of n:", n.shape)

p = np.matmul(m,n)
print("\n Matrix product: \n", p)
print("\n shape:", p.shape)

shape of m: (2, 3)
shape of n: (3, 3)

 Matrix product: 
 [[30  7 11]
 [52 15 23]]

 shape: (2, 3)
